routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/ravi', function () {
//     return view('welcome');
// });
Route::view('/report','reports.show');
Route::get('fees/report', 'StudentController@feesReport');
Route::get('importExport', 'ExcelController@importExport');
Route::get('showdata', 'ExcelController@showdata');
Route::get('downloadExcel/{type}', 'ExcelController@downloadExcel');
Route::post('importExcel', 'ExcelController@importExcel');

Route::post('mail/send', 'MailController@send');

Route::get('/', 'Controller@loadhome');
Route::get('roll/{id}', 'HomeController@roll');
Route::resource('all_rolllist', 'RollController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'CourseController');
Route::resource('syllabus', 'SyllabusController');
Route::resource('student', 'StudentController');
Route::get('admission/{id}', 'StudentController@admission');
Route::get('student_detail/{id}', 'StudentController@student_detail');
Route::post('admissionaction/{id}', 'StudentController@admissionaction');
Route::post('Fees/{id}', 'StudentController@fees_history');
Route::post('ajaxRequest', 'StudentController@ajaxRequestPost');
Route::post('ajaxRequestToCourses', 'ToolController@ajaxRequestToCourses');
Route::post('ajaxRequestmail', 'StudentController@ajaxRequestPostMail');
Route::resource('fee', 'FeesController');
Route::resource('aboutus', 'HomepageController');
Route::resource('service', 'ServiceControllerController');
Route::resource('review', 'CustomerReviewController');
Route::get('softdestroy/{id}', 'StudentController@softdestroy');
Route::resource('admin', 'AdminController');
Route::resource('mail', 'MailtemplateController');
Route::get('notif', 'StudentController@notif');
Route::get('changepassword', 'HomeController@changepass');
Route::get('tool', 'ToolController@index');
// Route::get('aboutus', 'Advertise@about');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'name',
        'email',
        'phone',
        'course',
        'reference',
        'status',
        'address',
        'city',
        'pin',
        'gender'
        
      ];

      public function fees()
      {
          return $this->hasMany('App\Fees', 'stusent_id', 'stusent_id');
      }

      public function admission()
      {
          return $this->hasMany('App\Admission', 'stusent_id', 'stusent_id');
      }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;
use App\Mail\SendMailable;
use Illuminate\Support\Facades\Mail;
use App\Student;
use App\Course;
use App\Admission;
use App\Fees;
use App\Logs;
use \DB;
use Auth;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {   
        
         $students = DB::table('students')
         ->select('students.name','students.status','students.email','students.reference','students.phone','students.id', DB::raw('COUNT(courses.name) as c_count'),DB::raw('sum(admissions.fees) as fees1'))
         ->join('courses','students.course','=','courses.id')
         ->join('admissions','students.id','=','admissions.student_id')
         ->groupBy('students.id', 'students.name','students.email','students.status','students.reference','students.phone')
         ->where('students.status','1')
         ->orderby('students.id','dese')
         ->get();
        // ->paginate(4);
         //$query=$students->toSql();
       // print_r($query);exit;
        return view('student.list_student', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
        $students = Student::all();
        // $students = Student::where('status', '=', 'NULL')->get();
        return view('student.add_student', compact('courses','students'));
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $uid = Auth::user()->id;
        //dd($uid);
        $c_id = $request->get('course');
        $feess = Course::find($c_id);
        $fees1 =  $feess->fees;
        $c_name = $feess->name;
      // print_r($_POST);exit();
       $request->validate([
        'name'=>'required',
        'email'=>'required',
        'phone'=>'required',
        'course'=>'required',
        'jdate'=>'required',
        'fees'=>'required',
        'pin'=>'required',
        'city'=>'required',
        'address'=>'required',
        'gender'=>'required',
        ]);
        

        $student = new Student([
        'name'=>  $request->get('name'),
        'email'=>  $request->get('email'),
        'phone'=>  $request->get('phone'),
        'status'=> 1,
        'course'=>  $request->get('course'),
        'reference'=>  $request->get('refe'),
        'address'=>  $request->get('address'),
        'pin'=>  $request->get('pin'),
        'city'=>  $request->get('city'),
        'gender'=>  $request->get('gender')
       
        ]);
        //print_r($student);dd($student);
        $student->save();
       

        $studen_id = DB::getPdo()->lastInsertId();
        $admission = new Admission([
            'student_id'=>  $studen_id,
            'course_id'=>  $request->get('course'),
            'date'=>  $request->get('jdate'),
            'fees'=>$fees1
            
            ]);
        $admission->save();
        $admission_id = DB::getPdo()->lastInsertId();
        $fees = new Fees([
                'student_id'=> $studen_id, 
                'admission_id'=>  $admission_id,
                'course_id'=>  $request->get('course'),
                'tdate'=>  $request->get('jdate'),
                'fees'=> $request->get('fees')
            ]);
            $fees->save();
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'New student add',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
    //    $pending = $fees1 - $request->get('fees');
    //    $objDemo = new \stdClass();
    //    $objDemo->fees = $request->get('fees');
    //    $objDemo->course = $c_name;
    //    $objDemo->pending = $pending;
    //    $objDemo->totalfees = $fees1;
    //    $objDemo->sender = 'Priyanka Bagde';
    //    $objDemo->receiver = $request->get('name');
    //    Mail::to($request->get('email'))->send(new SendMailable($objDemo));
       return redirect('/student')->with('success', 'Student has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $courses = Course::all();
        $student = Student::where('status','1')->where('id',$id)->firstOrFail();
        $data = ['courses'=>$courses,'student'=>$student];
        return view('student.edit_student', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
       $request->validate([
        'name'=>'required',
        'email'=>'required',
        'phone'=>'required'
        ]);
        

        $student = Student::find($id);
          $student->name = $request->get('name');
          $student->email = $request->get('email');
          $student->phone = $request->get('phone');
          $student->save();
          $uid = Auth::user()->id;
          $log = new Logs([
              'user_id'=>  $uid,
              'msg'=>'Student Update',
              'created_at'=> date('Y-m-d H:i:s')
          ]);
         $log->save();
          return redirect('/student')->with('success', 'Student has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $id)
    {
        $student = Student::find($id);
        $student->status = '0';
        $student->save();
        return redirect('/student')->with('success', 'Student has been Deleted');
    }
    public function softdestroy($id)
    {
        $student = Student::find($id);
        $student->status = '0';
        $student->save();
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'Student Delete',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
        return redirect('/student')->with('success', 'Student has been Deleted');
    }
    public function admission($id)
    {
        $courses = Course::all();
        $student = Student::find($id);
        $data = ['courses'=>$courses,'student'=>$student];

        return view('student.newadmission', compact('data'));
    }
    public function admissionaction(Request $request,$id){
            // print_r($_POST);exit();
            
       $request->validate([
        'name'=>'required',
        'email'=>'required',
        'phone'=>'required',
        'course'=>'required',
        'jdate'=>'required',
        'fees'=>'required',
        'course'=>'required'
        ]);
        $c_id = $request->get('course');
            $student = Course::find($c_id);
            $fees =  $student->fees;

        $admission = new Admission([
            'student_id'=>  $id,
            'course_id'=>  $request->get('course'),
            'date'=>  $request->get('jdate'),
            'fees'=> $fees
            ]);
        $admission->save();
        $admission_id = DB::getPdo()->lastInsertId();
        $fees = new Fees([
                'student_id'=> $id, 
                'admission_id'=>  $admission_id,
                'course_id'=>  $request->get('course'),
                'tdate'=>  $request->get('jdate'),
                'fees'=> $request->get('fees')
            ]);
            $fees->save();
            $uid = Auth::user()->id;
            $log = new Logs([
                'user_id'=>  $uid,
                'msg'=>'New Admission Added',
                'created_at'=> date('Y-m-d H:i:s')
            ]);
           $log->save();
        return redirect('/student')->with('success', 'New Course added');
    }

    public function student_detail($id){
        $sname = student::find($id);
        //print_r($sname);exit();
        // $balance = DB::table('fees')
        //              ->select(DB::raw('sum(fees) as fees'))
        //              ->where('course_id', '=', '1')
        //              ->where('student_id', '=', '1')
        //              ->first();
        //              echo $balance->fees;
        //              print_r($balance);
        
        // exit;
//$students = ['Course'=>$Course,'Fees'=>$Fees,'Admissions'=>$Admissions];
// echo "<pre>"; 
// print_r($result);exit; 
         $student = DB::select("SELECT courses.name as name,courses.id as c_id,admissions.fees as fees,admissions.date as date FROM courses LEFT JOIN admissions on courses.id = admissions.course_id WHERE admissions.student_id = '$id'");
         $students = ['sname'=>$sname,'student'=>$student];
        return view('student.detail_student', compact('students'));
    }
    public function fees_history(Request $request,$id){
        $s_id = $request->get('s_id');
        // $students = DB::select("");
        $fees = DB::table('fees')->where('student_id', '=', $s_id)
                    ->where('course_id', '=', $id)
                    ->get(); 

            // $fees = DB::table('fees')
            // ->where([
            //         ['student_id', '=', $s_id],
            //         ['course_id', '=', $id]
            //     ])->get();
                echo "<pre>";
        print_r($fees);
    }

    public function ajaxRequestPost(){

resources/views/student/detail_student.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
          
            <div class="card">
                <div class="card-header">
                <div class="row">
                <div class="col-md-5">
                <h2>{{$students['sname']->name}}</h2>
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
                </div>
                <div class="col-md-5" style="">
                <?php
                  $mails = DB::table('mailtemplates')->get();
                 // dd($mail);
                   
                  ?>
                   <div class="form-group">
                        <label for="name">Mail</label>
                        <select name="mail" class="form-control">
                        <option value="">--Select--</option>
                        @foreach ($mails as $mail)
                        <option value="{{$mail->id}}">{{ $mail->title }}</option>
                        @endforeach
                        </select>
                    </div>
                  
                </div>
                </div>
                
                @if(session()->get('success'))
                <div class="alert alert-success">
                {{ session()->get('success') }}  
                </div><br />
                @endif
                <input type="hidden" name="s_id" id="s_id" value="{{$students['sname']->id}}"/>
                </div>

                <div class="card-body">
               
                    <table class="table">
                    <thead>
                        <tr>
                            <th>SR</th>
                            <th>Courses</th>
                            <th>Total Fees</th>
                            
                            <th>Balance</th>
                            <th>Join Date</th>
                            <th>Fees History</th>
                            <th>Fees Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0;?>
                        @foreach($students['student'] as $student)
                        <?php $i++;?>
                        <tr>
                            <td>{{$i}}</td>
                            <td><a href="{{ route('courses.show',$student->c_id)}}"> {{$student->name}}</a></td>
                            <td>{{$student->fees}}</td>
                            <td><?php
                            $balance = DB::table('fees')
                              ->select(DB::raw('sum(fees) as fees'))
                              ->where('course_id', '=', $student->c_id)
                              ->where('student_id', '=', $students['sname']->id)
                              ->first();
                             
                            ?>{{$student->fees - $balance->fees }} </td>
                            <td>{{$student->date}}</td>
                            <td>
                            <button type="button" class="btn btn-info fees" data-toggle="modal" data-target="#myModal" lastid = "{{$student->c_id}}" >Fees History</button>
                            </td>
                            <td>
                           <?php 
                            
                            if($student->fees == $balance->fees){?>
                                    <button type="button" class="btn btn-info" disabled   >Pay Fees</button>
                           <?php }else{?>
                            <button type="button" class="btn btn-info fee"  lastid = "{{$student->c_id}}" >Pay Fees</button>

                          <?php }
                            ?>
                           
                            
                            </td>
                           
                        </tr>
                        @endforeach
                       
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


  
  
<div class="container">
 

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        <h4 class="modal-title"></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
         
        </div>
        <div class="modal-body">
          <div id ="fees">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
      
    </div>
  </div>
  <!--Model2--->
  <div id="myModal1" style="display:none;">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        <h4 class="modal-title"></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
         
        </div>
        <div class="modal-body">
         
          <form id="form1" action="{{URL ('fee') }}" method="POST">
              @csrf
              <div class="form-group">
                  
                  <input type="hidden" name = "sid" class="form-control" id="name1"  >
              </div>
              <div class="form-group">
                  
                  <input type="hidden" name = "cid" class="form-control" id="course1" >
              </div>
              
              
              <div class="form-group">
              <label for="fees">Pay Date</label>
                  <input type="date" name = "pdate" class="form-control" id="pay" placeholder="Enter Join Date">
              </div>
              <div class="form-group">
              <label for="fees">Fees</label>
                  <input type="text" name = "fees" class="form-control" id="fees" placeholder="Enter Fees">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
          </form>
          
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default close" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

<!--Model3--->
<div id="myModal3" style="display:none;">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        <h4 class="modal-title"></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
         
        </div>
        <div class="modal-body">
         
          <form id="form1" action="{{URL ('mail/send') }}" method="POST">
              @csrf
              
              <input type="hidden" name = "name" value="{{$students['sname']->name}}" >
              
              <div class="form-group">
              <label for="fees">To</label>
                  <input type="text" name = "to" class="form-control" id="to"  value="{{$students['sname']->email}}" >
              </div>
                <div class="form-group">
                <label for="fees">Subject</label>
                    <input type="text" name = "subject" class="form-control" id="subject" readonly >
                </div>
              <div class="form-group">
              <label for="fees">Mail body</label>
              <p>Note:-Please use &lt;br&gt; to break line</P>
                <textarea name="mailbody" id="mailbody" cols="30" rows="8"class="form-control"></textarea>
                 
              </div>
              <button type="submit" class="btn btn-primary">send</button>
          </form>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default close" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script>


   

$.ajaxSetup({

    headers: {

        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

    }

});



$(".fees").click(function(e){

    

    e.preventDefault();
   
    var c_id =$(this).attr('lastid')
    //alert(c_id);


     var s_id = $("input[name=s_id]").val();



    $.ajax({

       type:'POST',

       url:"{{url('/ajaxRequest')}}",

       data:{'s_id':s_id, 'c_id':c_id},

       success:function(data){
            $("#fees").html(data);
          

       }

    });



});

$(".fee").click(function(e){

    

e.preventDefault();

var c_id =$(this).attr('lastid')

//alert(c_id);


var s_id = $("input[name=s_id]").val();
$("#name1").val(s_id);
$("#course1").val(c_id);
$('#myModal1').css("display","block");
$('#myModal1').css("position","relative");
$('#myModal1').css("top","-200px");



});

$(".close").click(function(e){
  $('#form1')[0].reset();
  $('#myModal1').css("display","none");
  $('#myModal3').css("display","none");


});

$('select').on('change', function() {
  mail_id =  this.value ;
  $.ajax({

       type:'POST',

       url:"{{url('/ajaxRequestmail')}}",

       data:{'id':mail_id},

       success:function(data){
        var obj = JSON.parse(data);
        // alert(data);
        $('#mailbody').val(obj.body);
        $('#subject').val(obj.subject);
        $('#myModal3').css("display","block");
        $('#myModal3').css("position","relative");
        $('#myModal3').css("top","-200px");
          

       }

    });
});
</script>


  

@endsection

resources/views/student/edit1_admintion.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">New Admission
                <a class="nav-link" href="{{ URL ('/student') }}">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif
                <form name="myForm" id="myForm" action="{{ route('student.update', $data['student']->id) }}" method="POST">
                @csrf
                @method('PATCH')
                    <div class="form-group">
                        <label for="name">Student Name</label>
                        <input type="text" name = "name" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Student Name"  value="{{$data['student']->name}}">
                    </div>
                    <div class="form-group">
                        <label for="name">Student Email</label>
                        <input type="email" name = "email" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Student Name"  value="{{$data['student']->email}}"  >
                    </div>
                    <div class="form-group">
                        <label for="name">Student Phone No.</label>
                        <input type="text" name = "phone" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Student Phone No."  value="{{$data['student']->phone}}" >
                    </div>
                    <div class="form-group">
                        <label for="name">Courses Name</label>
                        <select name="course" class="form-control">
                        <option value="">--Select--</option>
                        @foreach ($data['courses'] as $course)
                        <option value="{{$course->id}}"<?php if($data['student']->course == $course->id) { ?> selected="selected"<?php } ?>>{{ $course->name }}</option>
                        
                        @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                    <label for="fees">Join Date</label>
                        <input type="date" name = "jdate" class="form-control" id="fees" placeholder="Enter Join Date"  value="{{$data['student']->joindate}}"  >
                    </div>
                    <div class="form-group">
                    <label for="fees">Fees</label>
                        <input type="text" name = "fees" class="form-control" id="fees" placeholder="Enter Fees" value="{{$data['student']->fees}}"  >
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
$(document).ready(function () {
$('#myForm').validate({ // initialize the plugin
 rules: {
     name: {
         required: true
        
     },
     email: {
         required: true,
         email: true
     },
     phone: {
         required: true
     },
     jdate: {
         required: true
     },
     fees: {
         required: true
     },
     course: {
         required: true
     }
 },
 messages:{
            name: {
                required: "Name is required"
            },
            email: {
                required: "Email-ID is required"
                
            },
            phone: {
                required: "Phone no. is required"
            },
            jdate: {
                required: "Joining-Date is required"
            },
            fees: {
                required: "Fees should nerver black"
            },
            course: {
                required: "Course is required"
            }
        }
});

});
</script>

@endsection

resources/views/student/edit_student.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">New Admission
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif
                <form name="myForm" id="myForm" action="{{ route('student.update', $data['student']->id) }}" method="POST">
                @csrf
                @method('PATCH')
                    <div class="form-group">
                        <label for="name">Student Name</label>
                        <input type="text" name = "name" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Student Name"  value="{{$data['student']->name}}">
                    </div>
                    <div class="form-group">
                        <label for="name">Student Email</label>
                        <input type="email" name = "email" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Student Name"  value="{{$data['student']->email}}"  >
                    </div>
                    <div class="form-group">
                        <label for="name">Student Phone No.</label>
                        <input type="text" name = "phone" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Student Phone No."  value="{{$data['student']->phone}}" >
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea  class="form-control" name ="address">{{$data['student']->address}}</textarea>
                    </div>
                    <div class="form-group">
                    <label for="gender">Gender</label>
                        <input type="radio" name = "gender" value="1" >Male
                        <input type="radio" name = "gender" value ="0">Female
                    </div>
                    <div class="form-group">
                    <label for="city">City</label>
                        <input type="text" name = "city" class="form-control" value="{{$data['student']->city}}">
                    </div>
                    <div class="form-group">
                    <label for="pin">Pin Code</label>
                        <input type="text" name = "pin" class="form-control" value="{{$data['student']->pin}}">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
$(document).ready(function () {
$('#myForm').validate({ // initialize the plugin
 rules: {
     name: {
         required: true
        
     },
     email: {
         required: true,
         email: true
     },
     phone: {
         required: true
     },
     jdate: {
         required: true
     },
     fees: {
         required: true
     },
     course: {
         required: true
     },
        address: {
            required: true
        
        },
        pin: {
            required: true
        
        },
        gender: {
            required: true
        },
        city:{
            required: true
        }
 },
 messages:{
            name: {
                required: "Name is required"
            },
            email: {
                required: "Email-ID is required"
                
            },
            phone: {
                required: "Phone no. is required"
            },
            jdate: {
                required: "Joining-Date is required"
            },
            fees: {
                required: "Fees should nerver black"
            },
            course: {
                required: "Course is required"
            }
        }
});

});
</script>

@endsection