routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/ravi', function () {
//     return view('welcome');
// });
Route::view('/report','reports.show');
Route::get('fees/report', 'StudentController@feesReport');
Route::get('importExport', 'ExcelController@importExport');
Route::get('showdata', 'ExcelController@showdata');
Route::get('downloadExcel/{type}', 'ExcelController@downloadExcel');
Route::post('importExcel', 'ExcelController@importExcel');

Route::post('mail/send', 'MailController@send');

Route::get('/', 'Controller@loadhome');
Route::get('roll/{id}', 'HomeController@roll');
Route::resource('all_rolllist', 'RollController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'CourseController');
Route::resource('syllabus', 'SyllabusController');
Route::resource('student', 'StudentController');
Route::get('admission/{id}', 'StudentController@admission');
Route::get('student_detail/{id}', 'StudentController@student_detail');
Route::post('admissionaction/{id}', 'StudentController@admissionaction');
Route::post('Fees/{id}', 'StudentController@fees_history');
Route::post('ajaxRequest', 'StudentController@ajaxRequestPost');
Route::post('ajaxRequestToCourses', 'ToolController@ajaxRequestToCourses');
Route::post('ajaxRequestmail', 'StudentController@ajaxRequestPostMail');
Route::resource('fee', 'FeesController');
Route::resource('aboutus', 'HomepageController');
Route::resource('service', 'ServiceControllerController');
Route::resource('review', 'CustomerReviewController');
Route::get('softdestroy/{id}', 'StudentController@softdestroy');
Route::resource('admin', 'AdminController');
Route::resource('mail', 'MailtemplateController');
Route::get('notif', 'StudentController@notif');
Route::get('changepassword', 'HomeController@changepass');
Route::get('tool', 'ToolController@index');
// Route::get('aboutus', 'Advertise@about');

app/Roll.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Roll extends Model
{
    protected $fillable = [
        'id', 'roll_name'
    ];
}

app/Http/Controllers/RollController.php
<?php

namespace App\Http\Controllers;

use App\Roll;
use App\Logs;
use Auth;
use \DB;
use Illuminate\Http\Request;

class RollController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $rolls = Roll::all();
        return view('rolls.all_rolllist',compact('rolls'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
       
        return view('rolls.create_roll');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $request->validate([
            'name'=>'required'
            ]);
            
    
            $roll = new Roll([
            'roll_name'=>  $request->get('name')
            ]);
            //print_r($student);dd($student);
            $roll->save();
        
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'New Role Added',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
       return redirect('/all_rolllist')->with('success', 'Role has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Roll  $roll
     * @return \Illuminate\Http\Response
     */
    public function show(Roll $roll)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Roll  $roll
     * @return \Illuminate\Http\Response
     */
    public function edit($id)    
    {  
       $roll = Roll::where('id',$id)->firstOrFail();
      
        return view('rolls.edit_roll',compact('roll'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Roll  $roll
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {   
        //print_r($id);exit;
        $request->validate([
            'name'=>'required'
            ]);
            
            $roll = Roll::find($id);
            $roll->roll_name = $request->get('name');
        
            $roll->save();
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'Role Edit',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
       return redirect('/all_rolllist')->with('success', 'Role has been Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Roll  $roll
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $roll = Roll::find($id);
        $roll->delete();
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'Role Delete',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
       return redirect('/all_rolllist')->with('success', 'Role has been Deleted');
    }
}

resources/views/rolls/all_rolllist.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                <h2>Admin Panel</h2>
                <a class="nav-link" href="{{ URL ('all_rolllist/create') }}">{{ __('Add Role') }}</a>
                </div>
                <div class="card-body">
                    <style>
                    .uper {
                        margin-top: 40px;
                    }
                    .tr ,td,th{
                        text-align:inherit;
                    }
                    </style>
                    <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div><br />
                    @endif
                    <table class="table-responsive">
                           
                    <thead>
                        <tr>
                            <th>SR</th>
                            <th>Name</th>
                            <th colspan="2">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php $i = 0;?>
                        @foreach($rolls as $roll)
                            <?php $i++;?>
                      
                            
                        <tr>

                            <td><?php echo $i;?></td>
                            <td>{{$roll->roll_name}} </a></td>
                            
                           
                            <td><a href="{{ route('all_rolllist.edit',$roll->id)}}" class="btn btn-primary">Edit</a></td>
                            {{-- <td > <a href="{{ URL ('softdestroy',$roll->id)}}" class="btn btn-danger">Delete</a></td> --}}
                            <td>   <form action="{{ route ('all_rolllist.destroy', $roll->id)}}" method="post" id ="myForm">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit" id="submit">Delete</button>
                                </form> 
                            </td>
                                
                            </td>
                        </tr>
                        @endforeach
                    
                        
                    </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/rolls/create_roll.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                <h2>Admin Panel</h2>
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                    @endif
                    <form name="myForm" id="myForm" action="{{URL ('all_rolllist') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="name">Role Name</label>
                            <input type="text" id = "name" name = "name" class="form-control"  aria-describedby="emailHelp" placeholder="Enter Roll Name">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
   
    
           <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
           <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
       <script>
        $(document).ready(function () {
        $('#myForm').validate({ // initialize the plugin
            rules: {
                name: {
                    required: true
                }
                
            },
            messages:{
                name: {
                    required: "Name is required"
                },
               
        });
       
    });
    </script>
    @endsection

resources/views/rolls/edit_roll.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                <h2>Admin Panel</h2>
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                    @endif
                   
                    <form name="myForm" id="myForm" action="{{ route('all_rolllist.update',$roll->id)}}" method="POST">
                            @csrf
                            @method('PATCH')
                      
                        <div class="form-group">
                            <label for="name">Role Name</label>
                           
                        <input type="text" id = "name" name = "name" class="form-control"  aria-describedby="emailHelp" value="{{$roll->roll_name}}">
                       
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Submit</button>
                        
                    </form>
                   
                </div>
            </div>
        </div>
    </div>
</div>
   
    
           <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
           <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
       <script>
        $(document).ready(function () {
        $('#myForm').validate({ // initialize the plugin
            rules: {
                name: {
                    required: true
                }
                
            },
            messages:{
                name: {
                    required: "Name is required"
                },
               
        });
       
    });
    </script>
    @endsection

resources/views/rolls/roll_list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                <h2> {{$rolls[0]['name']}}</h2>
                
                </div>
                <div class="card-body">
                    <style>
                    .uper {
                        margin-top: 40px;
                    }
                    .tr ,td,th{
                        text-align:inherit;
                    }
                    </style>
                    <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div><br />
                    @endif
                    <table class="table-responsive">
                           
                    <thead>
                        <tr>
                            <th>SR</th>
                            <th>Name</th>
                            <th colspan="2">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0;?>
                        @foreach($rolls as $roll)
                        <?php $i++; ?>
                        <tr>
 
                            <td>{{$i}}</td>
                            <td>{{$rolls[0]['name']}} </a></td>
                            
                           
                            <td><a href="{{ route('admin.edit',$rolls[0]['id'])}}" class="btn btn-primary">Edit</a></td>
                            <td > <a href="{{ URL ('user',$rolls[0]['id'])}}" class="btn btn-danger">Delete</a></td>
                                
                            </td>
                        </tr>
                    <?php //}?>
                        @endforeach
                    </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection