routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/ravi', function () {
//     return view('welcome');
// });
Route::view('/report','reports.show');
Route::get('fees/report', 'StudentController@feesReport');
Route::get('importExport', 'ExcelController@importExport');
Route::get('showdata', 'ExcelController@showdata');
Route::get('downloadExcel/{type}', 'ExcelController@downloadExcel');
Route::post('importExcel', 'ExcelController@importExcel');

Route::post('mail/send', 'MailController@send');

Route::get('/', 'Controller@loadhome');
Route::get('roll/{id}', 'HomeController@roll');
Route::resource('all_rolllist', 'RollController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'CourseController');
Route::resource('syllabus', 'SyllabusController');
Route::resource('student', 'StudentController');
Route::get('admission/{id}', 'StudentController@admission');
Route::get('student_detail/{id}', 'StudentController@student_detail');
Route::post('admissionaction/{id}', 'StudentController@admissionaction');
Route::post('Fees/{id}', 'StudentController@fees_history');
Route::post('ajaxRequest', 'StudentController@ajaxRequestPost');
Route::post('ajaxRequestToCourses', 'ToolController@ajaxRequestToCourses');
Route::post('ajaxRequestmail', 'StudentController@ajaxRequestPostMail');
Route::resource('fee', 'FeesController');
Route::resource('aboutus', 'HomepageController');
Route::resource('service', 'ServiceControllerController');
Route::resource('review', 'CustomerReviewController');
Route::get('softdestroy/{id}', 'StudentController@softdestroy');
Route::resource('admin', 'AdminController');
Route::resource('mail', 'MailtemplateController');
Route::get('notif', 'StudentController@notif');
Route::get('changepassword', 'HomeController@changepass');
Route::get('tool', 'ToolController@index');
// Route::get('aboutus', 'Advertise@about');

resources/views/courses/add_courses.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add New Courses
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
               
                </div>

                <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif
                <form name="myForm" id="myForm"  action="{{URL ('courses') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="name">Courses Name</label>
                        <input type="text" name = "name" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Courses Name">
                    </div>
                    <div class="form-group">
                        <label for="duration">Duration</label>
                        <input type="text" name = "duration" class="form-control" id="duration" placeholder="Enter Duration">
                    </div>
                    <div class="form-group">
                    <label for="fees">Fees</label>
                        <input type="text" name = "fees" class="form-control" id="fees" placeholder="Enter Fees">
                    </div>
                    <div class="form-group" >
                            <label for="fees">Level</label>
                            <select class="form-control" name='level' id='level'>
                                <option value=''>Select</option>
                                <option value='basic'>Basic</option>
                                <option value='pro'>Pro</option>
                                <option value='premium'>Premium</option>
                            </select>
                       </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $(".ref").click(function(){
        
        $("#refe").css("display","block");
        $(".ref").css("display","none");
    });
    
});
</script>
       <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
       <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
   <script>
    $(document).ready(function () {
    $('#myForm').validate({ // initialize the plugin
        rules: {
            name: {
                required: true
               
            },
            duration: {
                required: true
            },
            fees: {
                required: true
            },
            level: {
                required: true
            }
        },
        messages: {
            name: {
                required: "Course Name is required"
               
            },
            duration: {
                required: "Duration is required"
            },
            fees: {
                required: "Fees field never blank"
            },
            level: {
                required: "Level is required"
            }
        }
    });
   
});
</script>

@endsection

resources/views/courses/edit_courses.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Courses
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif
                <form name="myForm" id="myForm" method="post" action="{{ route('courses.update', $course->id) }}">
                    @method('PATCH')
                    @csrf
                    <div class="form-group">
                        <label for="name">Courses Name</label>
                        <input type="text" name = "name" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Courses Name"  value={{ $course->name }}>
                    </div>
                    <div class="form-group">
                        <label for="duration">Duration</label>
                        <input type="text"  name = "duration" class="form-control" id="duration" placeholder="Enter Duration"  value={{ $course->duration }}>
                    </div>
                    <div class="form-group">
                    <label for="free">Fees</label>
                        <input type="text"  name = "fees" class="form-control" id="free" placeholder="Enter Free"  value={{ $course->fees }}>
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
$(document).ready(function () {
$('#myForm').validate({ // initialize the plugin
 rules: {
     name: {
         required: true
        
     },
     duration: {
         required: true
     },
     fees: {
         required: true
     },
     level: {
         required: true
     }
 },
 messages: {
    name: {
        required: "Course Name is required"
        
    },
    duration: {
        required: "Duration is required"
    },
    fees: {
        required: "Fees field never blank"
    },
    level: {
        required: "Level is required"
    }
}
});

});
</script>

@endsection

resources/views/courses/list_courses.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                <h2>List Of Courses</h2>
                <a class="nav-link" href="{{ URL ('courses/create') }}">{{ __('Add Courses') }}</a>
                </div>

                <div class="card-body">
                    <style>
                    .uper {
                        margin-top: 0px;
                    }
                    </style>
                    <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div>
                    @endif
                    <table class="table-responsive">
                        
                    <thead>
                        <tr>
                            <th>SR</th>
                            <th>Courses Name</th>
                            <th>Courses Level</th>
                            <th>Duration</th>
                            <th>Fees</th>
                           
                            <th colspan="2">Action</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0;?>
                        @foreach($courses as $course)
                        <?php $i++;?>
                        <tr>
                            <td>{{$i}}</td>
                            <td><a href="{{ route('courses.show',$course->id)}}" >{{$course->name}}</a> </td>
                            <td>{{$course->level}}</td>
                            <td>{{$course->duration}} hours</td>
                            <td>Rs. {{$course->fees}}/-</td>
                            
                            <td><a href="{{ route('courses.edit',$course->id)}}" class="btn btn-primary">Edit</a></td>
                            <td >
                                <form action="{{ route('courses.destroy', $course->id)}}" method="post" id ="myForm">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit" id="submit">Delete</button>
                                </form>
                            </td>
                            
                        </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
  
    $('#myForm').submit(function() {
     
    var c = confirm("Click OK to continue?");
    return c; //you can just return c because it will be true or false
    });
});
</script>

@endsection

resources/views/courses/singel_courses.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h4>{{ $course[0]->name }}</h4>
                
                <a class="nav-link" href="{{ URL::previous() }}">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                    <div class="panel-body">
                        {!! $course[0]->syllabus!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection