routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/ravi', function () {
//     return view('welcome');
// });
Route::view('/report','reports.show');
Route::get('fees/report', 'StudentController@feesReport');
Route::get('importExport', 'ExcelController@importExport');
Route::get('showdata', 'ExcelController@showdata');
Route::get('downloadExcel/{type}', 'ExcelController@downloadExcel');
Route::post('importExcel', 'ExcelController@importExcel');

Route::post('mail/send', 'MailController@send');

Route::get('/', 'Controller@loadhome');
Route::get('roll/{id}', 'HomeController@roll');
Route::resource('all_rolllist', 'RollController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'CourseController');
Route::resource('syllabus', 'SyllabusController');
Route::resource('student', 'StudentController');
Route::get('admission/{id}', 'StudentController@admission');
Route::get('student_detail/{id}', 'StudentController@student_detail');
Route::post('admissionaction/{id}', 'StudentController@admissionaction');
Route::post('Fees/{id}', 'StudentController@fees_history');
Route::post('ajaxRequest', 'StudentController@ajaxRequestPost');
Route::post('ajaxRequestToCourses', 'ToolController@ajaxRequestToCourses');
Route::post('ajaxRequestmail', 'StudentController@ajaxRequestPostMail');
Route::resource('fee', 'FeesController');
Route::resource('aboutus', 'HomepageController');
Route::resource('service', 'ServiceControllerController');
Route::resource('review', 'CustomerReviewController');
Route::get('softdestroy/{id}', 'StudentController@softdestroy');
Route::resource('admin', 'AdminController');
Route::resource('mail', 'MailtemplateController');
Route::get('notif', 'StudentController@notif');
Route::get('changepassword', 'HomeController@changepass');
Route::get('tool', 'ToolController@index');
// Route::get('aboutus', 'Advertise@about');

app/Syllabus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Syllabus extends Model
{
    protected $fillable = [
        'syllabus',
        'course_id'
      ];
}

app/Http/Controllers/SyllabusController.php
<?php

namespace App\Http\Controllers;

use App\Syllabus;
use App\Course;
use \DB;
use App\Logs;
use Auth;
use Illuminate\Http\Request;

class SyllabusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
         $syllabus = DB::select("SELECT syllabi.*,courses.name FROM syllabi LEFT JOIN courses ON courses.id = syllabi.course_id");
        
         return view('Syllabus.Syllabus_list', compact('syllabus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
       
        return view('Syllabus.Syllabus_add', compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'syllabus'=>'required',
        'course'=>'required'
        ]);
        $syllabus = new Syllabus([
        'course_id'=>  $request->get('course'),
        'syllabus'=> $request->get('syllabus')
        ]);
       
        $syllabus->save();
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'New Syllabus Added',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
        return redirect('/syllabus')->with('success', 'Syllabus has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Syllabus  $syllabus
     * @return \Illuminate\Http\Response
     */
    public function show(Syllabus $syllabus)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Syllabus  $syllabus
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $courses = Course::all();
        $syllabus = Syllabus::find($id);
        $data = ['courses'=>$courses,'syllabus'=>$syllabus];

        return view('Syllabus.Syllabus_edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Syllabus  $syllabus
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'syllabus'=>'required',
            'course'=>'required'
          ]);
    
          $syllabus = Syllabus::find($id);
          $syllabus->course_id = $request->get('course');
          $syllabus->syllabus = $request->get('syllabus');
         
          $syllabus->save();
          $uid = Auth::user()->id;
          $log = new Logs([
              'user_id'=>  $uid,
              'msg'=>'Syllabus Update',
              'created_at'=> date('Y-m-d H:i:s')
          ]);
         $log->save();
          return redirect('/syllabus')->with('success', 'Syllabus has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Syllabus  $syllabus
     * @return \Illuminate\Http\Response
     */
    public function destroy(Syllabus $syllabus)
    {
        //
        $uid = Auth::user()->id;
        $log = new Logs([
            'user_id'=>  $uid,
            'msg'=>'Syllabus Delete',
            'created_at'=> date('Y-m-d H:i:s')
        ]);
       $log->save();
    }
}

resources/views/Syllabus/Syllabus_add.blade.php
@extends('layouts.app')

@section('content')

        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add New Courses
                <a class="nav-link" href="{{ URL ('/syllabus') }}">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif
                <form name="myForm" id="myForm" action="{{URL ('syllabus') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="name">Courses Name</label>
                        <select name="course" class="form-control">
                        <option value="">--Select--</option>
                        @foreach ($courses as $course)
                        <option value="{{$course->id}}">{{ $course->name }}</option>
                        @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="syllabus">syllabus</label>
                        <textarea name="syllabus" class="form-control" id="summary-ckeditor" cols="30" rows="10"></textarea>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
<script>
     $('textarea').ckeditor();;
</script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
$(document).ready(function () {
$('#myForm').validate({ // initialize the plugin
 rules: {
    course: {
         required: true
        
     }
 },
 messages: {
    course: {
         required: "Select Course"
        
     }
 }
});

});
</script>

@endsection

resources/views/Syllabus/Syllabus_edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Courses
                <a class="nav-link" href="{{ URL ('/syllabus') }}">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif

                
                <form name="myForm" id="myForm"  action="{{ route('syllabus.update', $data['syllabus']->id) }}" method="POST">
                @method('PATCH')
                    @csrf
                    <div class="form-group">
                        <label for="name">Courses Name</label>
                        <select name="course" class="form-control">
                        <option value="">--Select--</option>
                        @foreach ($data['courses'] as $course)
                        <option value="{{$course->id}}"<?php if($data['syllabus']->course_id == $course->id) { ?> selected="selected"<?php } ?>>{{ $course->name }}</option>
                        
                        @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="syllabus">Syllabus</label>
                        <textarea name="syllabus" class="form-control" id="summary-ckeditor" cols="30" rows="10">{{ $data['syllabus']->syllabus }}</textarea>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script>
    CKEDITOR.replace( 'summary-ckeditor' );
</script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
$(document).ready(function () {
$('#myForm').validate({ // initialize the plugin
 rules: {
    course: {
         required: true
        
     }
 },
 messages: {
    course: {
         required: "Select Course"
        
     }
 }
});

});
</script>
@endsection

resources/views/Syllabus/Syllabus_list.blade.php
@extends('layouts.app')

@section('content')
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script> -->
  <style>
       .panel-heading {
        background-color: #eee;
        color: #444;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
        transition: 0.4s;
        }
        .panel-heading:hover {
        background-color: #ccc; 
        }
        .panel-body {
        padding: 0 18px;
        background-color: white;
        overflow: hidden;
        }
  </style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                <h2>List Of Courses</h2>
                <a class="nav-link" href="{{ URL ('syllabus/create') }}">{{ __('Add Syllabus') }}</a>
                </div>

                <div class="card-body">
                    <style>
                    .uper {
                        margin-top: 40px;
                    }
                    </style>
                    <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div><br />
                    @endif
                    @foreach($syllabus as $syllb)
                    <div class="panel-group" id="accordion">
                
                        <div class="panel panel-default">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ $syllb->id }}">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    {{ $syllb->name }}
                                </h4>
                            </div>
                            </a>
                            <div id="collapse{{ $syllb->id }}" class="panel-collapse collapse">
                            <div class="panel-body">
                                {!! $syllb->syllabus!!}<br>
                                <a href="{{ route('syllabus.edit',$syllb->id)}}" >Edit</a>
                                <form action="{{ route('syllabus.destroy', $syllb->id)}}" method="post" id ="myForm">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit" id="submit">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    @endforeach

                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
  
    $('#myForm').submit(function() {
     
    var c = confirm("Click OK to continue?");
    return c; //you can just return c because it will be true or false
    });
});
</script>

  

@endsection